### PR TITLE
Mb

### PR DESCRIPTION
**Pull request by vidhishweta01**
we have finished our project with all the specification,Its responsive for tablet, laptop and mobile please give your valuable feedback.

### CODE REVIEW

**Comment by ashraffares** [comment]
@Julio Añoveros 
we are done with
we added a live demo
adding the same picture sizes
section centered 
corrected subscribe & newsletters sections
signup and newsletter responsive for tablet view 
we fixed the mobile view

thank you for your review

**Review by PhillipUg — CHANGES_REQUESTED** [review]
Hey team, 👋

You have done an amazing job implementing the requirements for this project.

However, there are still some changes 👇 you need to implement to approve this request 🔍

### Changes Required ♻️ 
- [x] First of all, kindly stop opening new pull requests while we are still reviewing the same project. It confuses reviewers. Please continue using the same pull request until project completion for all your future projects.
- [x] The titles of various items throughout the page should use hx tags (h1 - h6).
- [x] The hamburger icon in the Navbar, should only appear on tablet and mobile screen sizes
- [x] The social media icons in the footer should have links
- [x] The search input in the main navigation menu should be a form element
- [x] The Login and Subscribe buttons in the Navbar should have links too

#### Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack as **Phillip Musiime** or
 <a href="mailto:phillipmusiime@gmail.com"> gmail</a> &nbsp; &nbsp; [Twitter Follow](https://twitter.com/intent/follow?screen_name=Phillip_Ug) &nbsp; &nbsp; [GitHub followers](https://github.com/PhillipUg)

**Comment by ashraffares** [comment]
@PhillipUg 
we are done
thank you for your review 

add semantic tags hx
fix the hamburger icon
add links to social media icons
 added form to the search input 

thank you for your review

**Comment by ashraffares** [comment]
@PhillipUg
we are done
thank you for your review

add semantic tags hx
fix the hamburger icon
add links to social media icons
added form to the search input

thank you for your review

**Review by SpaYco — APPROVED** [review]
# Project Approved

thank you for making the required changes, your project is now approved!

- [ ] this is optional as it wasn't mentioned by the previous TSE, but please fix more of the CSS since there are a lot of CSS properties that can be a Bootstrap class instead, and this project is focused on that.

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Pull request merged**
